dist: xenial

language: ruby

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.0
  - ruby-head

brefore_install:
  - sudo apt-get update
  - sudo apt-get install libpng-dev libjpeg-dev

script:
  - bundle exec rake compile
  - bundle exec rake test
