# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{phashion}
  s.version = "1.0.4"
  s.authors = ["Mike Perham"]
  s.description = %q{Simple wrapper around the pHash library}
  s.email = %q{mperham@gmail.com}
  s.extensions = ["ext/phashion_ext/extconf.rb"]
  s.files = `git ls-files`.split("\n")
  s.homepage = %q{http://github.com/mperham/phashion}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.summary = %q{Simple wrapper around the pHash library}
  s.test_files = `git ls-files test`.split("\n")
  s.add_development_dependency(%q<rake-compiler>, [">= 0.7.0"])
end

